services:
  - type: web
    name: voter-verify-backend
    dockerfilePath: ./Dockerfile.backend
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false

  - type: web
    name: voter-verify-face
    dockerfilePath: ./Dockerfile
    runtime: docker
    envVars:
      - key: PORT
        value: 5001
      - key: BACKEND_URL
        sync: false
      - key: BACKEND_API_KEY
        sync: false
      - key: DEEPFACE_HOME
        value: /app/deepface_weights
      - key: PYTHONUNBUFFERED
        value: 1 